### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by tombrain** [Hy3n4/ha-cc-cometblue#12]
I get this three logentries:

First:
```
Logger: homeassistant.loader
Source: loader.py:786
First occurred: 20:17:45 (1 occurrences)
Last logged: 20:17:45

No 'version' key in the manifest file for custom integration 'cometblue'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'cometblue'
```
second:

```
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:557
Integration: Klima (documentation, issues)
First occurred: 20:17:45 (1 occurrences)
Last logged: 20:17:45

ClimateDevice is deprecated, modify CometBlueThermostat to extend ClimateEntity
```

third:
```
Logger: homeassistant.components.climate
Source: custom_components/cometblue/climate.py:85
Integration: Klima (documentation, issues)
First occurred: 20:17:45 (1 occurrences)
Last logged: 20:17:45

Error while setting up cometblue platform for climate
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/cometblue/climate.py", line 85, in setup_platform
    from cometblue import device as cometblue_dev
ModuleNotFoundError: No module named 'cometblue'
```

Like frist two logs, it seems, the extension is loaded

commonucation by shell woks:
```
(homeassistant) homeassistant@raspberrypi:~/.homeassistant/custom_components $ cometblue device -p 0 XX:XX:XX:XX:XX:XX get temperatures
Current temperature:	17.0 °C
Temperature for manual mode:	8.0 °C
Target temperature low:	8.0 °C
Target temperature high:	27.0 °C
Offset temperature:	0.0 °C
Window open sensitivity:	4 (1 = low, 4 = high, 8 = mid)
Window open minutes:	10
```

**Comment by danielkucera** [comment]
it seems hass is using different venv than where is your cometblue installed. 
Try to switch to it's venv and install cometblue:
```
source /srv/homeassistant/bin
pip3 install cometblue
```
