### ISSUE TITLE
Exception in callback _chain_future

### ISSUE THREAD

**Issue by danielkucera** [Hy3n4/ha-cc-cometblue#7]
Hi @Hy3n4 ,

do you have any idea what can cause this? It uses to happen few days after starting hass and I have to restart hass to get it working. I suspect the update thread to stuck on some blocking call. Can we somehow limit the update function execution time?

```
May 27 10:26:38 localhost hass[21620]: 2019-05-27 10:26:38 INFO (Thread-16) [custom_components.cometblue.climate] Update called B7:1E:5A:99:BF:21
May 27 10:26:38 localhost hass[21620]: 2019-05-27 10:26:38 INFO (Thread-16) [cometblue.device] Connecting to device "B7:1E:5A:99:BF:21"...
May 27 10:26:42 localhost hass[21620]: 2019-05-27 10:26:42 INFO (Thread-22) [cometblue.device] Unknown characteristics discovered on "B7:1E:5A:99:BF:21": ['00002a05-0000-1000-8000-00805f9b34fb', '47e9ee40-47e9-11e4-8939-164230d1df67']
May 27 10:26:48 localhost hass[21620]: 2019-05-27 10:26:48 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.living_room is taking over 10 seconds
May 27 10:27:07 localhost hass[21620]: 2019-05-27 10:27:07 ERROR (Thread-22) [cometblue.device] Value write failed for characteristic "47e9ee30-47e9-11e4-8939-164230d1df67" with error "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
May 27 10:27:07 localhost hass[21620]: 2019-05-27 10:27:07 DEBUG (Thread-16) [custom_components.cometblue.climate] _current.target_temp: 22.5
May 27 10:27:08 localhost hass[21620]: 2019-05-27 10:27:08 DEBUG (Thread-16) [custom_components.cometblue.climate] _current.target_temp diff: False
May 27 10:27:08 localhost hass[21620]: 2019-05-27 10:27:08 DEBUG (Thread-16) [custom_components.cometblue.climate] _current.target_temp_h diff: True
May 27 10:27:08 localhost hass[21620]: 2019-05-27 10:27:08 DEBUG (Thread-16) [custom_components.cometblue.climate] _current.target_temp_l diff: True
May 27 10:27:08 localhost hass[21620]: 2019-05-27 10:27:08 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback _chain_future.<locals>._set_state(<Future pendi...sk._wakeup()]>, <Future at 0x...StopIteration>) at /usr/lib/python3.5/asyncio/futures.py:446
May 27 10:27:08 localhost hass[21620]: Traceback (most recent call last):
May 27 10:27:08 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
May 27 10:27:08 localhost hass[21620]:     self._callback(*self._args)
May 27 10:27:08 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/futures.py", line 448, in _set_state
May 27 10:27:08 localhost hass[21620]:     _copy_future_state(other, future)
May 27 10:27:08 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/futures.py", line 424, in _copy_future_state
May 27 10:27:08 localhost hass[21620]:     dest.set_exception(exception)
May 27 10:27:08 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/futures.py", line 364, in set_exception
May 27 10:27:08 localhost hass[21620]:     raise TypeError("StopIteration interacts badly with generators "
May 27 10:27:08 localhost hass[21620]: TypeError: StopIteration interacts badly with generators and cannot be raised into a Future
May 27 10:31:31 localhost hass[21620]: 2019-05-27 10:31:31 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 10:36:32 localhost hass[21620]: 2019-05-27 10:36:32 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 10:41:33 localhost hass[21620]: 2019-05-27 10:41:33 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 10:43:51 localhost hass[21620]: 2019-05-27 10:43:51 ERROR (MainThread) [homeassistant.components.upc_connect.device_tracker] Error on 123
May 27 10:43:51 localhost hass[21620]: 2019-05-27 10:43:51 WARNING (MainThread) [homeassistant.components.upc_connect.device_tracker] Can't read device from 192.168.0.1
May 27 10:46:34 localhost hass[21620]: 2019-05-27 10:46:34 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 10:51:35 localhost hass[21620]: 2019-05-27 10:51:35 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 10:56:36 localhost hass[21620]: 2019-05-27 10:56:36 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 11:01:37 localhost hass[21620]: 2019-05-27 11:01:37 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 11:04:25 localhost hass[21620]: 2019-05-27 11:04:25 ERROR (MainThread) [homeassistant.components.upc_connect.device_tracker] Error on 123
May 27 11:04:25 localhost hass[21620]: 2019-05-27 11:04:25 WARNING (MainThread) [homeassistant.components.upc_connect.device_tracker] Can't read device from 192.168.0.1
May 27 11:06:38 localhost hass[21620]: 2019-05-27 11:06:38 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 11:11:39 localhost hass[21620]: 2019-05-27 11:11:39 INFO (Thread-11) [custom_components.cometblue.climate] Update called B7:1E:5A:99:BF:21
May 27 11:11:39 localhost hass[21620]: 2019-05-27 11:11:39 INFO (Thread-11) [cometblue.device] Connecting to device "B7:1E:5A:99:BF:21"...
May 27 11:11:39 localhost hass[21620]: 2019-05-27 11:11:39 DEBUG (Thread-11) [custom_components.cometblue.climate] _current.target_temp: 22.5
May 27 11:11:39 localhost hass[21620]: 2019-05-27 11:11:39 DEBUG (Thread-11) [custom_components.cometblue.climate] _current.target_temp diff: False
May 27 11:11:39 localhost hass[21620]: 2019-05-27 11:11:39 DEBUG (Thread-11) [custom_components.cometblue.climate] _current.target_temp_h diff: True
May 27 11:11:39 localhost hass[21620]: 2019-05-27 11:11:39 DEBUG (Thread-11) [custom_components.cometblue.climate] _current.target_temp_l diff: True
May 27 11:11:39 localhost hass[21620]: 2019-05-27 11:11:39 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback _chain_future.<locals>._set_state(<Future pendi...sk._wakeup()]>, <Future at 0x...StopIteration>) at /usr/lib/python3.5/asyncio/futures.py:446
May 27 11:11:39 localhost hass[21620]: Traceback (most recent call last):
May 27 11:11:39 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
May 27 11:11:39 localhost hass[21620]:     self._callback(*self._args)
May 27 11:11:39 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/futures.py", line 448, in _set_state
May 27 11:11:39 localhost hass[21620]:     _copy_future_state(other, future)
May 27 11:11:39 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/futures.py", line 424, in _copy_future_state
May 27 11:11:39 localhost hass[21620]:     dest.set_exception(exception)
May 27 11:11:39 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/futures.py", line 364, in set_exception
May 27 11:11:39 localhost hass[21620]:     raise TypeError("StopIteration interacts badly with generators "
May 27 11:11:39 localhost hass[21620]: TypeError: StopIteration interacts badly with generators and cannot be raised into a Future
```

**Comment by danielkucera** [comment]
Ok, the problem is that when the device is not reachable, it throws exception which is not caught (and not visible in the above output)
```
May 30 11:36:02 localhost hass[5580]: 2019-05-30 11:36:02 DEBUG (Thread-17) [custom_components.cometblue.climate] update exception
May 30 11:36:02 localhost hass[5580]: 2019-05-30 11:36:02 DEBUG (Thread-17) [custom_components.cometblue.climate] Unable to connect & resolve the device
```
One possible solotion is:
```
-        self._thermostat.attempt_to_get_ready()
-        with self._thermostat as device:
+        if not self._thermostat.attempt_to_get_ready():
+            _LOGGER.info("Device {} not ready".format(self._mac))
+            return
```

but the communication can also fail anytime later so I would prefer:
```
         """Update the data from the thermostat."""
         get_temperatures = True
         _LOGGER.info("Update called {}".format(self._mac))
-        self._thermostat.connect()
-        self._thermostat.attempt_to_get_ready()
-        with self._thermostat as device:
+        try:
+          with self._thermostat as device:
             if self._current.mode_code != self._target.mode_code and self._target.manual is not None:
                 _LOGGER.debug("Setting mode to: {}".format(self._target.mode_value))
                 device.set_status(self._target.mode_value)
@@ -441,6 +440,9 @@ class CometBlueThermostat(ClimateDevice):
                 _LOGGER.debug("Current Firmware Revision: {}".format(self._current.firmware_rev))
                 _LOGGER.debug("Current Software Revision: {}".format(self._current.software_rev))
                 _LOGGER.debug("Current Manufacturer Name: {}".format(self._current.manufacturer))
+        except Exception as e:
+            _LOGGER.debug("update exception")
+            _LOGGER.debug(str(e))
         self._thermostat.disconnect()
         if self._target.target_temp is not None:
             self._current.target_temp = self._target.target_temp
```

@Hy3n4 , what do you think?
